/*
 * BaiY js library
 * Copyright(c) BaiYang [http://baiy.cn], 2010 - 2017, all rights reserved.
 */

var BAIY={};(function(){BAIY.stRootOfLibbaiy="libbaiy";BAIY.HasNS=function(a){try{if(typeof a!=="string")return!1;if(window[a]&&typeof window[a]==="object")return!0}catch(b){}return!1}})();
(function(){function a(c){for(var a=[],b=c.length*8,e=0;e<b;e+=8)a[e>>5]|=(c.charCodeAt(e/8)&255)<<24-e%32;return a}function b(c){for(var a="",b=c.length*32,e=0;e<b;e+=8)a+=String.fromCharCode(c[e>>5]>>>24-e%32&255);return a}function c(c,a){void 0===a&&(a=!1);for(var b=a?"0123456789ABCDEF":"0123456789abcdef",e="",f=c.length*4,j=0;j<f;++j){var d=c[j>>2];e+=b.charAt(d>>(3-j%4)*8+4&15)+b.charAt(d>>(3-j%4)*8&15)}return e}function e(c,a){function b(d,c){var l=(d&65535)+(c&65535);return(d>>16)+(c>>16)+
(l>>16)<<16|l&65535}c[a>>5]|=128<<24-a%32;c[(a+64>>9<<4)+15]=a;for(var e=Array(80),f=1732584193,j=-271733879,d=-1732584194,o=271733878,l=-1009589776,q=0;q<c.length;q+=16){for(var t=f,u=j,p=d,v=o,w=l,n=0;n<80;n++){e[n]=n<16?c[q+n]:(e[n-3]^e[n-8]^e[n-14]^e[n-16])<<1|(e[n-3]^e[n-8]^e[n-14]^e[n-16])>>>31;var r=f<<5|f>>>27,s;s=n<20?j&d|~j&o:n<40?j^d^o:n<60?j&d|j&o|d&o:j^d^o;r=b(b(r,s),b(b(l,e[n]),n<20?1518500249:n<40?1859775393:n<60?-1894007588:-899497514));l=o;o=d;d=j<<30|j>>>2;j=f;f=r}f=b(f,t);j=b(j,
u);d=b(d,p);o=b(o,v);l=b(l,w)}return[f,j,d,o,l]}function f(c,b){var f=a(c);f.length>16&&(f=e(f,c.length*8));for(var k=Array(16),m=Array(16),j=0;j<16;++j){var d=f[j];k[j]=d^909522486;m[j]=d^1549556828}f=e(k.concat(a(b)),512+b.length*8);return e(m.concat(f),672)}BAIY.CRYPTO={};BAIY.CRYPTO.HASH={};BAIY.CRYPTO.HASH.HexSha1=function(b,f){return c(e(a(b),b.length*8),f)};BAIY.CRYPTO.HASH.BlobSha1=function(c){return b(e(a(c),c.length*8))};BAIY.CRYPTO.HASH.Sha1UnitTest_=function(){return BAIY.CRYPTO.HASH.HexSha1("abc",
!1)=="a9993e364706816aba3e25717850c26c9cd0d89d"};BAIY.CRYPTO.MAC={};BAIY.CRYPTO.MAC.HexHmacSha1=function(b,a,e){return c(f(b,a),e)};BAIY.CRYPTO.MAC.BlobHmacSha1=function(c,a){return b(f(c,a))}})();
(function(){function a(c){for(var b="",a=0,h,g=[],i;c.nPos<c.stCsv.length;++c.nPos)switch(i=c.stCsv.charAt(c.nPos),a){case 0:b="";h=!1;if(i==c.cQuo)a=2;else if(i==c.cDlm){g.push("");break}else if(i==c.cNl)if(0==g.length){c.nPos+=c.stNl.length-1;break}else return c.nPos+=c.stNl.length,g.push(""),g;else b+=i,a=1;break;case 1:if(i==c.cDlm)g.push(b),a=0;else if(i==c.cNl)return g.push(b),c.nPos+=c.stNl.length,g;else b+=i;break;case 2:if(i==c.cQuo)h?(h=!1,b+=c.cQuo):h=!0;else if(h)if(g.push(b),i==c.cDlm)a=
0;else return i==c.cNl?(c.nPos+=c.stNl.length,g):!1;else b+=i;break;default:return!1}switch(a){case 0:i==c.cDlm&&g.push("");break;case 1:g.push(b);break;case 2:if(h)g.push(b);else return!1}return g}function b(c,b,a,h,g,i){function k(d){if(-1!=d.indexOf(g))return!0;else if(-1!=d.indexOf(i))return!0;for(var c=0;c<h.length;++c){var b=h.charAt(c);if(-1!=d.indexOf(b))return!0}return!1}if(!c.length)return"";for(var b=b?h:"",m=0;m<c.length;++m){var j=c[m];typeof j!="string"&&(j=j.toString());if(2==a||1==
a&&0==j.length||k(j)){b+=i;for(var d=0;d<j.length;++d){var o=j.charAt(d);b+=o;i==o&&(b+=i)}b+=i}else b+=j;m+1!=c.length&&(b+=g)}return b}BAIY.CSV={};BAIY.CSV.Import=function(c,b,f,h){var g=[];if(!c)return g;b||(b="\r\n");f||(f=",");h||(h='"');var i={};i.stCsv=c;i.stNl=b;i.cNl=b.charAt(0);i.cDlm=f;i.cQuo=h;for(i.nPos=0;;){c=a(i);if(!c||!c.length)break;g.push(c)}return g};BAIY.CSV.QT_IN_DEMAND=0;BAIY.CSV.QT_WITH_EMPTY=1;BAIY.CSV.QT_ALWAYS=2;BAIY.CSV.Export=function(c,a,f,h,g){var i="";if(!c.length)return i;
if(void 0===a)a=BAIY.CSV.QT_IN_DEMAND;f||(f="\r\n");h||(h=",");g||(g='"');for(var k=0;k<c.length;++k)i+=b(c[k],0!=k,a,f,h,g);return i}})();
(function(){function a(d,c){if(0==d.length)return!1;return d.charAt(d.length-1)==c}function b(d,c){for(;a(d,c);)d=d.substr(0,d.length-1);return d}function c(d,c){if(0==d.length)return!1;return d.charAt(0)==c}function e(d){for(var c=0;c<d.length;++c){var b=d.charAt(c);if(!j.hasOwnProperty(b))break}if(0!=c)return d.substr(c);return d}function f(d){for(var c=d.length;c!=0;--c){var b=d.charAt(c-1);if(!j.hasOwnProperty(b))break}if(c<d.length)return d.substr(0,c);return d}function h(d,c,b){for(var a=0;a<
c.length;++a){var e=c[a];if(!(4>e.length)){var f=e[0],h=e[1];switch(e[2]){case "KEY":d.CreateSubkey(f);break;case "STRING":d.WriteString(f,h,e[3],!1);break;case "STRING_EXP":d.WriteString(f,h,e[3],!0);break;case "BLOB":d.WriteBlob(f,h,BAIY.CConfig.HexToBlob(e[3]));break;case "DWORD":d.WriteDWord(f,h,e[3]);break;case "QWORD":d.WriteQWord(f,h,e[3]);break;case "STRING_SET":d.WriteVStr(f,h,b(e[3]));break;case "FLOAT":d.WriteDouble(f,h,e[3]);break;case "BOOL":d.WriteBool(f,h,e[3])}}}}function g(d,c,b){0!=
b.length&&d.push([b,"","KEY",""]);for(stValName in c.tblValues){var a=c.tblValues[stValName],e,f;switch(a.eType){case 1:e=a.mixValue;f="STRING";break;case 2:e=a.mixValue;f="STRING_EXP";break;case 3:e=BAIY.CConfig.BlobToHex(a.mixValue,!0,"");f="BLOB";break;case 4:e=""+a.mixValue;f="DWORD";break;case 5:e=a.mixValue;f="QWORD";break;case 6:e=a.mixValue;f="STRING_SET";break;case 7:e=""+a.mixValue;f="FLOAT";break;case 8:e=a.mixValue?"yes":"no";f="BOOL";break;default:continue}d.push([b,a.stNameWithCase,
f,e])}for(stKeyName in c.tblSubkeys)a=c.tblSubkeys[stKeyName],g(d,a,0==b.length?a.stNameWithCase:b+"\\"+a.stNameWithCase)}function i(d){function c(d){var a={stNext:"",stRest:""},e=d.indexOf("\\");if(-1==e)return a.stNext=d,a;a.stNext=b(d,"\\");if(e<a.stNext.length-1)a.stRest=a.stNext.substr(e+1),a.stNext=a.stNext.substr(0,e);return a}for(d=c(d);0==d.stNext.length;)if(0==d.stRest.length)return d.bIsEmpty=!0,d;else d=c(d.stRest);d.bIsEmpty=!1;d.stNextWithCase=d.stNext;d.stNext=d.stNext.toLowerCase();
return d}function k(d,c,a,b){throw"BAIY.CConfig.prototype."+d+" - invalid type\n  subkey path = "+c+"\n  value name  = "+a+"\n  value type  = "+BAIY.CConfig.TypeToStr(b);}function m(d,c,a){for(prop in c)if(a||!d.hasOwnProperty(prop))typeof c[prop]=="object"?(d[prop]=c[prop]instanceof Array?[]:{},m(d[prop],c[prop],a)):d[prop]=c[prop]}var j={" ":!0,"\t":!0,"\r":!0,"\n":!0};BAIY.CConfig=function(){this.m_iKey=1==arguments.length?arguments[0]:{stNameWithCase:"",tblSubkeys:{},tblValues:{}}};BAIY.CConfig.TYPE_STRING=
1;BAIY.CConfig.TYPE_STRING_EXP=2;BAIY.CConfig.TYPE_BLOB=3;BAIY.CConfig.TYPE_DWORD=4;BAIY.CConfig.TYPE_QWORD=5;BAIY.CConfig.TYPE_STRING_SET=6;BAIY.CConfig.TYPE_DOUBLE=7;BAIY.CConfig.TYPE_BOOL=8;BAIY.CConfig.TypeToStr=function(d){switch(d){case 1:return"STRING";case 2:return"STRING_EXP";case 3:return"BLOB";case 4:return"DWORD";case 5:return"QWORD";case 6:return"STRING_SET";case 7:return"FLOAT";case 8:return"BOOL";default:return"unknown"}};BAIY.CConfig.HexToBlob=function(d){function c(d){return d>=48&&
d<=57?d-48:d>=65&&d<=70?d-65+10:d>=97&&d<=102?d-97+10:-1}if(!d)return"";for(var a=d.length-1,b="",e=0;e<a;++e){var f=c(d.charCodeAt(e));-1!=f&&(f<<=4,f+=c(d.charCodeAt(++e)),b+=String.fromCharCode(f))}return b};BAIY.CConfig.BlobToHex=function(d,c,a){if(!d)return"";void 0===c&&(c=!0);typeof a!=="string"&&(a=" ");for(var c=c?"0123456789ABCDEF":"0123456789abcdef",b="",e=0;e<d.length;++e){0!=e&&(b+=a);var f=d.charCodeAt(e),h=f&15;b+=c.charAt((f&240)>>4);b+=c.charAt(h)}return b};BAIY.CConfig.DWordToSigned=
function(d){return d<2147483648?d:-(~d+1)};BAIY.CConfig.QWordToSigned=function(d){"string"==typeof d&&(d=parseInt(d));if(d<9223372036854775E3)return d;else{var c=Math.floor(d/4294967296),d=~(d-c*4294967296);0>d&&(d&=2147483647,d+=2147483648);return~c*-4294967296-d-1}};BAIY.CConfig.prototype.OpenJson=function(d){this.Clear();if(!d)return!0;d=eval(d);if(!d.length)return!1;h(this,d,function(d){return eval(d)});return!0};BAIY.CConfig.prototype.OpenCsv=function(d){this.Clear();if(!d)return!0;d=BAIY.CSV.Import(d,
"\r\n",",",'"');if(!d.length)return!1;h(this,d,function(d){return BAIY.CSV.Import(d,"\n",";","`")[0]});return!0};BAIY.CConfig.prototype.OpenIni=function(d){function b(d){d.stLine="";for(var c=d.nPos=0;h.stData.length!=h.nPos;){var a=h.stData.charAt(h.nPos++);if(a=="\r\n".charAt(c)){if(1==c)return!0;++c}else d.stLine+=a,c=0}return 0!=d.stLine.length}function l(d,c){for(var a="",b=!1;d.nPos<d.stLine.length;++d.nPos){var e=d.stLine.charAt(d.nPos);if(b)switch(b=!1,e){case "r":a+="\r";break;case "n":a+=
"\n";break;default:a+=e}else if(e=="~")b=!0;else if(e==c){++d.nPos;break}else a+=e}return a}this.Clear();if(!d)return!0;for(var h={stData:d,nPos:0},d={stLine:"",nPos:0},g="";b(d);)if(d.stLine=e(f(d.stLine)),0!=d.stLine.length&&!c(d.stLine,";")&&!c(d.stLine,"#"))if(c(d.stLine,"[")&&a(d.stLine,"]"))d.nPos=1,g=l(d,"\0"),g=g.substr(0,g.length-1),this.CreateSubkey(g);else{var i=l(d,":"),p=l(d,"="),p=e(f(p)).toUpperCase();0==p.length&&(p="STRING");switch(p){case "STRING":this.WriteString(g,i,l(d,"\0"),
!1);break;case "STRING_EXP":this.WriteString(g,i,l(d,"\0"),!0);break;case "BLOB":this.WriteBlob(g,i,BAIY.CConfig.HexToBlob(l(d,"\0")));break;case "DWORD":this.WriteDWord(g,i,l(d,"\0"));break;case "QWORD":this.WriteQWord(g,i,l(d,"\0"));break;case "FLOAT":this.WriteDouble(g,i,l(d,"\0"));break;case "BOOL":this.WriteBool(g,i,l(d,"\0"));break;case "STRING_SET":for(p=[];d.nPos<d.stLine.length;)p[p.length]=l(d,"|");this.WriteVStr(g,i,p)}}return!0};BAIY.CConfig.prototype.SaveJson=function(d){function c(d){for(var a=
d.length,b="",e=0;e<a;++e){var l=d.charAt(e);switch(l){case "\r":b+="\\r";break;case "\n":b+="\\n";break;case "\t":b+="\\t";break;case "\u0008":b+="\\b";break;case "\u000c":b+="\\f";break;case '"':b+='\\"';break;case "\\":b+="\\\\";break;default:b+=l}}return b}d||(d="");var a=[];g(a,this.m_iKey,"");if(!a.length)return"[]";for(var b="["+d,e=0;e<a.length;++e)if(!(a[e].length<4)){var f=a[e];b+='["'+c(f[0])+'",';b+='"'+c(f[1])+'",';b+='"'+f[2]+'",';if(f[2]!="STRING_SET")b+='"'+c(f[3])+'"]';else{b+='"[';
for(var f=f[3],h=0;h<f.length;++h)b+='\\"'+c(c(f[h]))+'\\"',h!=f.length-1&&(b+=",");b+=']"]'}e!=a.length-1&&(b+=",");b+=d}b+="]";return b};BAIY.CConfig.prototype.SaveCsv=function(){var d=[];g(d,this.m_iKey,"");if(!d.length)return"";for(var c=BAIY.CSV,b=0;b<d.length;++b)d[b].length>=4&&d[b][2]=="STRING_SET"&&(d[b][3]=c.Export(Array(d[b][3]),0,"\n",";","`"));return c.Export(d)};BAIY.CConfig.prototype.SaveIni=function(){function d(d){for(var c="",b=0;b<d.length;++b){var a=d.charAt(b);switch(a){case "\r":c+=
"~r";continue;case "\n":c+="~n";continue;case "~":c+="~"}c+=a}return c}function c(a,e){0!=e.length&&(b+="\r\n["+e+"]\r\n");for(stValName in a.tblValues){var f=a.tblValues[stValName],h,g=f.stNameWithCase;h="";if(0!=g.length){var i=g.charAt(0);switch(i){case "#":case ";":case "[":h+="~"}}for(var j=0;j<g.length;++j){i=g.charAt(j);switch(i){case "\r":h+="~r";continue;case "\n":h+="~n";continue;case ":":case "~":h+="~"}h+=i}switch(f.eType){case 1:h+=":STRING="+d(f.mixValue);break;case 2:h+=":STRING_EXP="+
d(f.mixValue);break;case 3:h+=":BLOB="+BAIY.CConfig.BlobToHex(f.mixValue,!0," ");break;case 4:h+=":DWORD="+f.mixValue;break;case 5:h+=":QWORD="+f.mixValue;break;case 6:h+=":STRING_SET=";for(g=0;g<f.mixValue.length;++g){0!=g&&(h+="|");for(var i=f.mixValue[g],j="",k=0;k<i.length;++k){var m=i.charAt(k);switch(m){case "\r":j+="~r";continue;case "\n":j+="~n";continue;case "|":case "~":j+="~"}j+=m}h+=j}break;case 7:h+=":FLOAT="+f.mixValue;break;case 8:h+=":BOOL="+(f.mixValue?"yes":"no");break;default:continue}b+=
h+"\r\n"}for(stKeyName in a.tblSubkeys)f=a.tblSubkeys[stKeyName],g=d(f.stNameWithCase),c(f,0==e.length?g:e+"\\"+g)}var b="";c(this.m_iKey,"");return b};BAIY.CConfig.prototype.Clear=function(){this.m_iKey.tblValues={};this.m_iKey.tblSubkeys={}};BAIY.CConfig.prototype.ClearValues=function(){this.m_iKey.tblValues={}};BAIY.CConfig.prototype.ClearSubkeys=function(){this.m_iKey.tblSubkeys={}};BAIY.CConfig.prototype.IsSubkeyExist=function(d){d=i(d);if(d.bIsEmpty)return!0;if(this.m_iKey.tblSubkeys.hasOwnProperty(d.stNext)){if(0==
d.stRest.length)return!0;return(new BAIY.CConfig(this.m_iKey.tblSubkeys[d.stNext])).IsSubkeyExist(d.stRest)}return!1};BAIY.CConfig.prototype.CreateSubkey=function(d){this.GainSubkey(d)};BAIY.CConfig.prototype.GainSubkey=function(d){d=i(d);if(d.bIsEmpty)return this;this.m_iKey.tblSubkeys.hasOwnProperty(d.stNext)||(this.m_iKey.tblSubkeys[d.stNext]={stNameWithCase:d.stNextWithCase,tblSubkeys:{},tblValues:{}});var c=new BAIY.CConfig(this.m_iKey.tblSubkeys[d.stNext]);if(0==d.stRest.length)return c;return c.GainSubkey(d.stRest)};
BAIY.CConfig.prototype.ObtainSubkey=function(d){var c=i(d);if(c.bIsEmpty)return this;if(this.m_iKey.tblSubkeys.hasOwnProperty(c.stNext)){d=new BAIY.CConfig(this.m_iKey.tblSubkeys[c.stNext]);if(0==c.stRest.length)return d;return d.ObtainSubkey(c.stRest)}throw"BAIY.CConfig.prototype.GainSubkey - can not find specified subkey\n  next subkey = "+c.stNext+"\n  full path   = "+d;};BAIY.CConfig.prototype.ObtainSubkeyIfExist=function(d){return this.IsSubkeyExist(d)?this.ObtainSubkey(d):new BAIY.CConfig};
BAIY.CConfig.prototype.RemoveSubkey=function(d){if(this.IsSubkeyExist(d)){var a={stPre:"",stFianl:""};for(a.stPre=b(d,"\\");c(d,"\\");)d=d.substr(1);a.stPre=d;d=a.stPre.lastIndexOf("\\");-1==d?(a.stFianl=a.stPre,a.stPre=""):(a.stFianl=a.stPre.substr(d+1),a.stPre=a.stPre.substr(0,d));0!=a.stPre.length?this.GainSubkey(a.stPre).RemoveSubkey(a.stFianl):0!=a.stFianl.length&&delete this.m_iKey.tblSubkeys[a.stFianl.toLowerCase()]}};BAIY.CConfig.prototype.DetachSubkey=function(d){if(!this.IsSubkeyExist(d))return new BAIY.CConfig;
var c=this.GainSubkey(d);this.RemoveSubkey(d);return c};BAIY.CConfig.prototype.EnumSubkey=function(d,c){for(stName in this.m_iKey.tblSubkeys)d(this,this.m_iKey.tblSubkeys[stName].stNameWithCase,c)};BAIY.CConfig.prototype.GetAllSubkeys=function(d){function c(d,a,b,e){for(stName in a.tblSubkeys){var f=a.tblSubkeys[stName],l=e+f.stNameWithCase;d.push(l);b&&c(d,f,!0,l+"\\")}}void 0===d&&(d=!0);var a=[];c(a,this.m_iKey,d,"");return a};BAIY.CConfig.prototype.IsValueExist=function(d,c){if(0==d.length)return this.m_iKey.tblValues.hasOwnProperty(c.toLowerCase());
if(!this.IsSubkeyExist(d))return!1;return this.ObtainSubkey(d).IsValueExist("",c)};BAIY.CConfig.prototype.GetValueType=function(d,c){if(0==d.length){var a=c.toLowerCase();if(this.m_iKey.tblValues.hasOwnProperty(a))return this.m_iKey.tblValues[a].eType;else throw"BAIY.CConfig.prototype.GetValueType - value does not exist\n  value name = "+c;}if(!this.IsSubkeyExist(d))throw"BAIY.CConfig.prototype.GetValueType - subkey does not exist\n  subkey path = "+d;return this.ObtainSubkey(d).GetValueType("",c)};
BAIY.CConfig.prototype._GetRawValue=function(d,c){if(0==d.length){var a=c.toLowerCase();return this.m_iKey.tblValues.hasOwnProperty(a)?this.m_iKey.tblValues[a]:!1}if(!this.IsSubkeyExist(d))return!1;return this.ObtainSubkey(d)._GetRawValue("",c)};BAIY.CConfig.prototype.ReadString=function(d,c,a){var b=this._GetRawValue(d,c);if(!b)return a||"";1!=b.eType&&2!=b.eType&&k("ReadString",d,c,b.eType);return b.mixValue};BAIY.CConfig.prototype.ReadBlob=function(d,c,a){var b=this._GetRawValue(d,c);if(!b)return a||
"";3!=b.eType&&k("ReadBlob",d,c,b.eType);return b.mixValue};BAIY.CConfig.prototype.ReadDWord=function(d,c,a){var b=this._GetRawValue(d,c);if(!b)return a||0;4!=b.eType&&k("ReadDWord",d,c,b.eType);return b.mixValue};BAIY.CConfig.prototype.ReadQWord=function(d,c,a){var b=this._GetRawValue(d,c);if(!b)return""+(a||"0");5!=b.eType&&k("ReadQWord",d,c,b.eType);return b.mixValue};BAIY.CConfig.prototype.ReadVStr=function(d,c,b){var a=this._GetRawValue(d,c);if(!a)return b=b||[];6!=a.eType&&k("ReadVStr",d,c,
a.eType);return a.mixValue};BAIY.CConfig.prototype.ReadDouble=function(d,c,a){var b=this._GetRawValue(d,c);if(!b)return a||0;7!=b.eType&&k("ReadDouble",d,c,b.eType);return b.mixValue};BAIY.CConfig.prototype.ReadBool=function(d,c,b){var a=this._GetRawValue(d,c);if(!a)return b||!1;8!=a.eType&&k("ReadBool",d,c,a.eType);return a.mixValue};BAIY.CConfig.prototype._SetRawValue=function(d,c,a){0==d.length?(a.stNameWithCase=c,this.m_iKey.tblValues[c.toLowerCase()]=a):this.GainSubkey(d)._SetRawValue("",c,a)};
BAIY.CConfig.prototype.WriteString=function(c,a,b,e){this._SetRawValue(c,a,{eType:e?2:1,mixValue:""+b})};BAIY.CConfig.prototype.WriteBlob=function(c,a,b){this._SetRawValue(c,a,{eType:3,mixValue:b})};BAIY.CConfig.prototype.WriteDWord=function(c,a,b){switch(typeof b){case "string":b=e(b);if(0==b.length||"0"==b)b=0;else if(-1!=String("+-123456789").indexOf(b.charAt(0)))b=parseInt(b,10);else switch(b.charAt(0)){case "x":case "X":b=parseInt(b.substr(1),16);break;case "b":case "B":b=parseInt(b.substr(1),
2);break;case "0":switch(b.charAt(1)){case "x":case "X":b=parseInt(b.substr(2),16);break;case "b":case "B":b=parseInt(b.substr(2),2);break;default:b=parseInt(b.substr(1),8)}break;default:b=0}isNaN(b)&&(b=0);break;case "boolean":b=b?1:0;break;case "number":break;default:b=0}this._SetRawValue(c,a,{eType:4,mixValue:b})};BAIY.CConfig.prototype.WriteQWord=function(c,b,a){switch(typeof a){case "string":var a=e(f(a)),h=0,g=10;if(0==a.length||"0"==a)a="0";else if(-1==String("+-123456789").indexOf(a.charAt(0)))switch(a.charAt(0)){case "x":case "X":h=
1;g=16;break;case "b":case "B":h=1;g=2;break;case "0":switch(a.charAt(1)){case "x":case "X":h=2;g=16;break;case "b":case "B":g=h=2;break;default:h=1,g=8}break;default:a="0"}h=parseInt(a.substr(h),g);isNaN(h)&&(a="0");break;case "boolean":a=a?"1":"0";break;case "number":a=""+a;break;default:a="0"}this._SetRawValue(c,b,{eType:5,mixValue:a})};BAIY.CConfig.prototype.WriteVStr=function(c,b,a){if(!(a instanceof Array))switch(typeof a){case "string":a=[a];break;default:a=[]}this._SetRawValue(c,b,{eType:6,
mixValue:a})};BAIY.CConfig.prototype.WriteDouble=function(c,b,a){switch(typeof a){case "string":a=e(a);a=parseFloat(a);isNaN(a)&&(a=0);break;case "boolean":a=a?1:0;break;case "number":break;default:a=0}this._SetRawValue(c,b,{eType:7,mixValue:a})};BAIY.CConfig.prototype.WriteBool=function(a,c,b){switch(typeof b){case "string":if(0!=b.length)switch(b.charAt(0)){case "t":case "T":case "y":case "Y":b=!0;break;default:b=!1}else b=!1;break;case "number":b=0!=b;break;case "boolean":break;default:b=!1}this._SetRawValue(a,
c,{eType:8,mixValue:b})};BAIY.CConfig.prototype.RemoveValue=function(a,b){if(0==a.length){var c=b.toLowerCase();this.m_iKey.tblValues.hasOwnProperty(c)&&delete this.m_iKey.tblValues[c]}else this.IsSubkeyExist(a)&&this.ObtainSubkey(a).RemoveValue("",b)};BAIY.CConfig.prototype.EnumValue=function(a,b){for(stName in this.m_iKey.tblValues)a(this,this.m_iKey.tblValues[stName].stNameWithCase,b)};BAIY.CConfig.prototype.GetAllValues=function(a){function b(a,c,d,e){for(stName in c.tblValues)a.push({stKey:e,
stValue:c.tblValues[stName].stNameWithCase});if(d)for(stKeyName in c.tblSubkeys)d=c.tblSubkeys[stKeyName],b(a,d,!0,e+d.stNameWithCase+"\\")}void 0===a&&(a=!0);var c=[];b(c,this.m_iKey,a,"");return c};BAIY.CConfig.prototype.IsEmpty=function(){for(stName in this.m_iKey.tblValues)return!1;for(stName in this.m_iKey.tblSubkeys)return!1;return!0};BAIY.CConfig.prototype.HasSubkey=function(){for(stName in this.m_iKey.tblSubkeys)return!0;return!1};BAIY.CConfig.prototype.HasValue=function(){for(stName in this.m_iKey.tblValues)return!0;
return!1};BAIY.CConfig.prototype.Equals=function(a){if(!a.hasOwnProperty("m_iKey"))return!1;return this.m_iKey==a.m_iKey};BAIY.CConfig.prototype.CheckCircularReferernce=function(){function a(b,c){for(stName in b.tblSubkeys){keySub=b.tblSubkeys[stName];if(keySub.tblSubkeys===c.tblSubkeys)throw"BAIY.CConfig.prototype.CheckCircularReferernce - circular reference detected\n  subkey = "+keySub.stNameWithCase;a(keySub,c)}}a(this.m_iKey,this.m_iKey)};BAIY.CConfig.prototype.Export=function(a,b){void 0===
b&&(b=!0);void 0===a&&(a="");if(0==a.length){var c={stNameWithCase:"",tblSubkeys:{},tblValues:{}};m(c.tblValues,this.m_iKey.tblValues,!0);b&&m(c.tblSubkeys,this.m_iKey.tblSubkeys,!0);return new BAIY.CConfig(c)}return this.GainSubkey(a).Export("",b)};BAIY.CConfig.prototype.Import=function(a,b,c,e){void 0===c&&(c=!0);void 0===e&&(e=!0);if(0==a.length){if(m(this.m_iKey.tblValues,b.m_iKey.tblValues,e),c)for(stKeyName in b.m_iKey.tblSubkeys)a=b.m_iKey.tblSubkeys[stKeyName].stNameWithCase,this.GainSubkey(a).Import("",
b.ObtainSubkey(a),!0,e)}else return this.GainSubkey(a).Import("",b,c,e)};BAIY.CConfig.prototype.Replace=function(a,b,c){void 0===c&&(c=!0);0==a.length?(this.ClearValues(),m(this.m_iKey.tblValues,b.m_iKey.tblValues,!0),c&&(this.ClearSubkeys(),m(this.m_iKey.tblSubkeys,b.m_iKey.tblSubkeys,!0))):this.GainSubkey(a).Replace("",b,c)};BAIY.CConfig.prototype.Insert=function(a,b){0==a.length?(this.m_iKey.tblSubkeys=b.m_iKey.tblSubkeys,this.m_iKey.tblValues=b.m_iKey.tblValues):this.GainSubkey(a).Insert("",b)}})();
(function(){BAIY.CLangPack=function(a){this.m_iLpk=a};BAIY.CLangPack.prototype.Merge=function(a,b){void 0===b&&(b=!0);var c=this.m_iLpk;for(stValue in a)if("_HEADER"!=stValue&&(b||!c.hasOwnProperty(stValue)))c[stValue]=a[stValue]};BAIY.CLangPack.prototype.GetJsonValue=function(){return this.m_iLpk};BAIY.CLangPack.prototype.GetLpkName=function(){return this.m_iLpk._HEADER.Name};BAIY.CLangPack.prototype.GetLpkEnglishName=function(){return this.m_iLpk._HEADER.AsciiName};BAIY.CLangPack.prototype.GetLpkCanonicalNames=
function(){return this.m_iLpk._HEADER.CanonicalName};BAIY.CLangPack.prototype.GetLpkCodePages=function(){return this.m_iLpk._HEADER.CodePage};BAIY.CLangPack.prototype.GetLpkOriginEncode=function(){return this.m_iLpk._HEADER.OriginEncode};BAIY.CLangPack.prototype.GetLpkReadDirection=function(){return this.m_iLpk._HEADER.ReadDirection};BAIY.CLangPack.prototype.GetLpkAppName=function(){return this.m_iLpk._HEADER.AppName};BAIY.CLangPack.prototype.GetTag=function(a){var b=this.m_iLpk;if(null==b[a]||typeof b[a]!==
"object")return"";a=b[a].Tag;if(null==a)return"";return a};BAIY.CLangPack.prototype.GetTitle=function(a,b){null==b&&(b=0);var c=this.m_iLpk;if(null==c[a]||typeof c[a]!=="object")return a;c=c[a].Title;if(null==c||null==c[b])return a;return c[b]};BAIY.CLangPack.prototype._=BAIY.CLangPack.prototype.GetTitle;BAIY.CLangPack.prototype.GetTip=function(a,b){null==b&&(b=0);var c=this.m_iLpk;if(null==c[a]||typeof c[a]!=="object")return"";c=c[a].Tip;if(null==c||null==c[b])return"";return c[b]};BAIY.CLangPack.prototype.$=
BAIY.CLangPack.prototype.GetTip;BAIY.CLangPack.prototype.GetHelp=function(a,b){null==b&&(b=0);var c=this.m_iLpk;if(null==c[a]||typeof c[a]!=="object")return"";c=c[a].Help;if(null==c||null==c[b])return"";return c[b]};BAIY.CLangPack.prototype.GetData=function(a,b,c){null==b&&(b=0);null==c&&(c=!0);var e=this.m_iLpk;if(null==e[a]||typeof e[a]!=="object")return"";a=e[a].Data;if(null==a||null==a[b])return"";if(c){b=a[b];c="";for(a=0;a<b.length;a+=2)e=parseInt(b.substr(a,2),16),c+=String.fromCharCode(e);
return c}return a[b]}})();
(function(){function a(a,b){var c=document.getElementsByTagName("HEAD")[0],g=document.createElement("script");g.language="javascript";g.type="text/javascript";g.id=a;g.text=b;c.appendChild(g)}BAIY.IO={};var b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=null;BAIY.IO.NewXhr=function(){if(null!=c)return c();for(var a=0;a<b.length;++a)try{var f=b[a],h=f();if(h!=null)return sg_fnFactory=f,h}catch(g){}c=
function(){throw"XMLHttpRequest not supported";};c()};BAIY.IO.LoadJs=function(b){if(!document.getElementById(b)){var c=BAIY.IO.NewXhr();c.open("GET",b,!1);c.send(null);if(200!=c.status){var h="BAIY.IO.LoadJs - failed retirve the url\n";h+="  url             = "+b+"\n";h+="  response status = "+c.status+" "+c.statusText;throw h;}a(b,c.responseText)}};BAIY.IO.LoadJsAsync=function(b,c){if(document.getElementById(b))return!1;var h=BAIY.IO.NewXhr();h.onreadystatechange=function(){if(4==h.readyState)if(200!=
h.status){var g="BAIY.IO.LoadJsAsync - failed retirve the url\n";g+="  url             = "+b+"\n";g+="  response status = "+h.status+" "+h.statusText;c(b,!1,g)}else try{a(b,h.responseText),c(b,!0,"")}catch(i){c(b,!1,i)}};h.open("GET",b,!0);h.send(null);return!0};BAIY.IO.LoadJsFromOtherSite=function(b,a){if(document.getElementById(b))return!1;var c=document.getElementsByTagName("HEAD")[0],g=document.createElement("script");g.language="javascript";g.type="text/javascript";if(a)g.onload=g.onreadystatechange=
function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")g.onload=g.onreadystatechange=null,a(b)};g.id=b;g.src=b;c.appendChild(g);return!0};BAIY.IO.LoadCss=function(b){if(!document.getElementById(b)){var a=document.getElementsByTagName("HEAD")[0],c=document.createElement("link");c.type="text/css";c.rel="stylesheet";c.id=b;c.href=b;a.appendChild(c)}};BAIY.IO.RemoveCss=function(b){(b=document.getElementById(b))&&document.getElementsByTagName("HEAD")[0].removeChild(b)}})();
(function(){BAIY.STR={};BAIY.STR.CompileRule=function(b,a){if(""==b)return function(){return!0};void 0===a&&(a=!0);var e=a?"i":"";if("/"==b.charAt(0))b=b.substr(1);else{for(var f="",h=!1,g=0;g<b.length;++g){var i=b.charAt(g);if(h)switch(h=!1,i){case "\\":f+="\\\\";break;case "?":case "*":f+="\\"+i;break;case "^":case "$":case ".":case "+":case "=":case "!":case ":":case "|":case "/":case "(":case ")":case "[":case "]":case "{":case "}":f+="\\\\\\"+i;break;default:f+="\\\\"+i}else switch(i){case "\\":h=
!0;break;case "?":f+=".";break;case "*":f+="."+i;break;case "^":case "$":case ".":case "+":case "=":case "!":case ":":case "|":case "/":case "(":case ")":case "[":case "]":case "{":case "}":f+="\\"+i;break;default:f+=i}}b=f}var k=RegExp(b,e);return function(b){return k.test(b)}};var a=null;BAIY.STR.ResetCharcodeMap=function(b){var c=!1;if(b)for(stChar in b){c=!0;break}c?(a=function(b){for(var c="",h=0;h<b.length;++h){var g=b.charAt(h).toLocaleLowerCase(),i=a.tblCodeMapping[g];c+=void 0!==i?"\u00ff"+
i:g}return c},a.tblCodeMapping=b,BAIY.STR.LocaleCompare=function(b,c){b=a(b);c=a(c);return b.localeCompare(c)}):b?(a=function(b){return b.toLocaleLowerCase()},BAIY.STR.LocaleCompare=function(b,a){b=b.toLocaleLowerCase();a=a.toLocaleLowerCase();return b.localeCompare(a)}):(a=null,BAIY.STR.LocaleCompare=function(b,a){return b.localeCompare(a)})};BAIY.STR.SortTable=function(b,c){if(!b||!b.length)return!0;if(!c||!c.length)return!1;b.sort(a?function(b,f){for(var h=0;h<c.length;++h){var g=c[h].col,i=b[g],
g=f[g];typeof i=="string"?(i=a(i),g=a(g),i=i.localeCompare(g)):i=i>g?1:i<g?-1:0;if(0!=i)return c[h].desc?-i:i}return 0}:function(b,a){for(var h=0;h<c.length;++h){var g=c[h].col,i=b[g],g=a[g],i=typeof i=="string"?i.localeCompare(g):i>g?1:i<g?-1:0;if(0!=i)return c[h].desc?-i:i}return 0});return!0};BAIY.STR.LocaleCompare=function(b,a){return b.localeCompare(a)};BAIY.STR.RetriveHeaderVarible=function(b,a,e){if(!b)return"";void 0===a&&(a="");var f=b.indexOf(a);if(-1==f)return"";f+=a.length;a=b.length;
if(void 0!==e&&(a=b.indexOf(e,f),-1==a))a=b.length;return b.substring(f,a)};BAIY.STR.RetriveCookieVarible=function(b){if(!b)return"";return BAIY.STR.RetriveHeaderVarible(document.cookie,b+"=",";")};BAIY.STR.SetCookieVarible=function(b,a,e,f,h,g){if(b&&a)b=b+"="+encodeURIComponent(a),e&&e>0&&(a=new Date,a.setTime(a.getTime()+e*864E5),b+="; expires="+a.toUTCString()),h&&(b+="; domain="+h),b+="; path="+(f?f:"/"),g&&(b+="; secure"),document.cookie=b};BAIY.STR.RemoveCookieVarible=function(b,a,e){if(b)b+=
"=; expires=Thu, 01 Jan 1970 00:00:00 GMT",e&&(b+="; domain="+e),b+="; path="+(a?a:"/"),document.cookie=b}})();
(function(){BAIY.CKeywordTree=function(){this.m_tblDict={mixVal:null,tblNext:{}}};BAIY.CKeywordTree.prototype.SetItem=function(a,b){for(var a=""+a,c=this.m_tblDict,e=0;e<a.length;++e){var f=a.charCodeAt(e),h=c.tblNext[f];void 0!==h?c=h:(c.tblNext[f]={mixVal:null,tblNext:{}},c=c.tblNext[f])}c.mixVal=b};BAIY.CKeywordTree.prototype.Match=function(a){for(var a=""+a,b=null,c=this.m_tblDict,e=0;e<a.length;++e){var f=a.charCodeAt(e),c=c.tblNext[f];if(void 0===c)break;if(null!=c.mixVal)b=c.mixVal}if(null==
b&&null!=this.m_tblDict.mixVal)b=this.m_tblDict.mixVal;return b};BAIY.CKeywordTree.prototype.HasNodeBeginWith=function(a){for(var a=""+a,b=this.m_tblDict,c=0;c<a.length;++c){var e=a.charCodeAt(c),b=b.tblNext[e];if(void 0===b)return!1}return!0};BAIY.CKeywordTree.prototype.GetItem=function(a){for(var a=""+a,b=this.m_tblDict,c=0;c<a.length;++c){var e=a.charCodeAt(c),b=b.tblNext[e];if(void 0===b)break;if(a.length-1==c&&null!=b.mixVal)return b.mixVal}return null};BAIY.CApiNexus=function(){this.m_tblBufferQueue=
{};this.m_tblApiProc={}};BAIY.CApiNexus.prototype.RegisterProcessor=function(a,b,c){if(b){this.m_tblApiProc[a]={proc:b,scope:c};var e=this.m_tblBufferQueue[a];if(e){for(;0!=e.length;)c?b.call(c,e.shift()):b(e.shift());delete this.m_tblBufferQueue[a]}}else delete this.m_tblApiProc[a]};BAIY.CApiNexus.prototype.MakeCall=function(a,b){var c=this.m_tblApiProc[a];if(c&&c.proc)return c.scope?c.proc.call(c.scope,b):c.proc(b);else throw"BAIY.CApiNexus.prototype.MakeCall - api does not exist\n  api = "+a;};
BAIY.CApiNexus.prototype.PostCall=function(a,b){var c=this.m_tblApiProc[a];return c&&c.proc?(c.scope?c.proc.call(c.scope,b):c.proc(b),!0):((c=this.m_tblBufferQueue[a])?c.push(b):this.m_tblBufferQueue[a]=[b],!1)};BAIY.CApiNexus.prototype.HasProcessor=function(a){return this.m_tblApiProc.hasOwnProperty(a)};BAIY.CApiNexus.prototype.ClearBufferQueue=function(a){!a||""==a?this.m_tblBufferQueue={}:delete this.m_tblBufferQueue[a]};BAIY.CTaskQueue=function(a,b,c){this.m_queTasks=[];this.m_fnDone=null;this.m_tblVars=
{};a&&this.AppendTask(a,b,c)};BAIY.CTaskQueue.prototype.AppendTask=function(a,b,c){if(b)a.iThisObj=b;if(c)a.iArgs=c;this.m_queTasks.push(a)};BAIY.CTaskQueue.prototype.BatchAppendTasks=function(a){if(a&&a.length)for(var b=0;b<a.length;++b)this.AppendTask(a[b].task,a[b].scope,a[b].args)};BAIY.CTaskQueue.prototype.PrependTask=function(a,b,c){if(b)a.iThisObj=b;if(c)a.iArgs=c;this.m_queTasks.unshift(a)};BAIY.CTaskQueue.prototype.BatchPrependTasks=function(a){if(a&&a.length)for(var b=a.length-1;0<=b;--b)this.PrependTask(a[b].task,
a[b].scope,a[b].args)};BAIY.CTaskQueue.prototype.SetFinallyCallback=function(a,b,c){if(a){if(b)a.iThisObj=b;if(c)a.iArgs=c;this.m_fnDone=a}else this.m_fnDone=null};BAIY.CTaskQueue.prototype.GoNext=function(){function a(a,c){a.iThisObj?a.call(a.iThisObj,b,a.iArgs,c):a(b,a.iArgs,c)}var b=this;if(this.m_queTasks.length)try{a(this.m_queTasks.shift())}catch(c){if(this.m_fnDone){var e=this.m_fnDone;this.m_fnDone=null;a(e,c)}else throw c;}else if(this.m_fnDone)e=this.m_fnDone,this.m_fnDone=null,a(e)};BAIY.CTaskQueue.prototype.ThrowError=
function(a){if(!this.m_fnDone)throw a;var b=this.m_fnDone;this.m_fnDone=null;try{b.iThisObj?b.call(b.iThisObj,this,b.iArgs,a):b(this,b.iArgs,a)}catch(c){throw this.Clear(),c;}this.Clear()};BAIY.CTaskQueue.prototype.GetVar=function(a,b){if(this.m_tblVars.hasOwnProperty(a))return this.m_tblVars[a];return void 0===b?null:b};BAIY.CTaskQueue.prototype.SetVar=function(a,b){void 0===b&&this.m_tblVars.hasOwnProperty(a)&&delete this.m_tblVars[a];this.m_tblVars[a]=b};BAIY.CTaskQueue.prototype.IsVarExist=function(a){return this.m_tblVars.hasOwnProperty(a)};
BAIY.CTaskQueue.prototype.Clear=function(){this.m_queTasks=[];this.m_tblVars={};this.m_fnDone=null}})();
(function(){function a(){if(-1==c){var a=navigator.userAgent;c=BAIY.HasNS("WeixinJSBridge")||/micromessenger/i.test(a)?1:/MQQBrowser/i.test(a)?2:0}}BAIY.PLAT={};BAIY.PLAT.Swap16=function(a){return(a&255)<<8|a>>8&255};BAIY.PLAT.Swap32=function(a){return(a&255)<<24|(a&65280)<<8|a>>8&65280|a>>24&255};var b=-1;BAIY.PLAT.HasLongPollingSupport=function(){if(-1==b){var a=navigator.userAgent;b=a.indexOf("Safari/")!=-1&&BAIY.MOB.IsOnIos()&&a.indexOf("OS 6_")&&-1==a.indexOf("CriOS/")?0:1}return 0!=b};var c=
-1;BAIY.PLAT.IsTengxunEnv=function(){a();return 0!=c};BAIY.PLAT.IsInWeixinEnv=function(){a();return 1==c};BAIY.PLAT.IsInQQEnv=function(){a();return 2==c};BAIY.PLAT.HookTengxunEnv=function(){if(BAIY.PLAT.IsTengxunEnv())String.prototype.localeCompare=function(a,b){return a<b?-1:a>b};else try{"abc123".localeCompare("efg456")}catch(a){String.prototype.localeCompare=function(a,b){return a<b?-1:a>b}}};BAIY.PLAT.SetScaledBackground=function(a,b){if(a){b||(b=document.getElementsByTagName("body")[0]);var c=
"position:absolute; background-image: url(";c+=a+"); ";c+="width:100%; height:100%; background-size:100% 100%; ";c+="-moz-background-size:100% 100%; ";if(navigator.userAgent.indexOf("MSIE ")!=-1){c+="filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='";c+=a+"', sizingMethod='scale')";var g="baiy-scaled-bg-for-"+b.getAttribute("id"),i=document.getElementById(g);i||(i=document.createElement("div"),i.setAttribute("id",g),b.insertBefore(i,b.firstChild));i.style.cssText=c;return i}else return b.setAttribute("style",
c),b}}})();
(function(){function a(){-1==c&&(c=navigator.platform.indexOf("iPad")!=-1?65537:navigator.platform.indexOf("iPhone")!=-1?65538:navigator.platform.indexOf("iPod")!=-1?65540:navigator.userAgent.indexOf("Android")!=-1?131072:0)}function b(a){function b(a,c){k=c.changedTouches[0];var e=document.createEvent("MouseEvent");e.initMouseEvent(a,!0,!0,k.view,1,k.screenX,k.screenY,k.clientX,k.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null);return e}function c(a,b){var e=b.screenX-a.screenX,f=b.screenY-
a.screenY;return e*e+f*f}if(!(a.changedTouches.length!=1&&a.touches.length!=1)){var k=a.changedTouches[0],m="";switch(a.type){case "touchstart":e=b("mousedown",a);f=!0;return;case "touchmove":m="mousemove";break;case "touchend":m="mouseup";break;default:m="mouseup"}if(e){if("mousemove"!=m){f=!1;e=null;return}if(c(e,k)<256)return;k.target.dispatchEvent(e);e=null}if(f){var j=b(m,a);k.target.dispatchEvent(j)||a.preventDefault();"mousemove"!=m&&(f=!1)}}}BAIY.MOB={};var c=-1;BAIY.MOB.IsMobileRuntime=function(){a();
return 0!=c};BAIY.MOB.IsOnIos=function(){a();return 0!=(c&65536)};BAIY.MOB.IsIpadDevice=function(){a();return 65537==c};BAIY.MOB.IsOnAndroid=function(){a();return 0!=(c&131072)};var e=null,f=!1;BAIY.MOB.InstallDragDropEmulator=function(){BAIY.MOB.IsMobileRuntime()&&(document.addEventListener("touchstart",b,!0),document.addEventListener("touchmove",b,!0),document.addEventListener("touchend",b,!0),document.addEventListener("touchcancel",b,!0))};BAIY.MOB.UninstallDragDropEmulator=function(){document.removeEventListener("touchstart",
b,!0);document.removeEventListener("touchmove",b,!0);document.removeEventListener("touchend",b,!0);document.removeEventListener("touchcancel",b,!0)}})();
(function(){BAIY.EVT={};BAIY.EVT.StartHookMouseDown=function(a){document.addEventListener?document.addEventListener(BAIY.MOB.IsMobileRuntime()?"touchstart":"mousedown",a,!0):document.attachEvent?document.attachEvent("onmousedown",a):document.onmousedown=a};BAIY.EVT.StopHookMouseDown=function(a){document.addEventListener?document.removeEventListener(BAIY.MOB.IsMobileRuntime()?"touchstart":"mousedown",a,!0):document.attachEvent?document.detachEvent("onmousedown",a):document.onmousedown=null};BAIY.EVT.StartHookMouseUp=
function(a){document.addEventListener?document.addEventListener(BAIY.MOB.IsMobileRuntime()?"touchend":"mouseup",a,!0):document.attachEvent?document.attachEvent("onmouseup",a):document.onmouseup=a};BAIY.EVT.StopHookMouseUp=function(a){document.addEventListener?document.removeEventListener(BAIY.MOB.IsMobileRuntime()?"touchend":"mouseup",a,!0):document.attachEvent?document.detachEvent("onmouseup",a):document.onmouseup=null}})();
